on:
  workflow_dispatch:
    inputs:
        appVersion:
          description: 'UEAssetToolkitGenerator Version And Release Tag'
          required: true
          default: '0.0.X'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Fetch Submodules Recursively
        run: git submodule update --init --recursive
        

      - name: .NET 6 Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: .NET Restore
        run: dotnet restore FModel

      - name: .NET Publish
        run: dotnet publish CookedAssetSerializerGUI -c Release --no-self-contained -r win-x64 -f net7.0-windows -o "./CookedAssetSerializerGUI/bin/Publish/" -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:DebugType=None -p:GenerateDocumentationFile=false -p:DebugSymbols=false -p:AssemblyVersion=${{ github.event.inputs.appVersion }} -p:FileVersion=${{ github.event.inputs.appVersion }}

      - name: ZIP File
        uses: papeloto/action-zip@v1
        with:
          files: ./CookedAssetSerializerGUI/bin/Publish/*
          dest: UEAssetToolkitGeneratorv${{ github.event.inputs.appVersion }}.zip # will end up in working directory not the Publish folder

      - name: GIT Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "UEAssetToolKitGenerator v${{ github.event.inputs.appVersion }}"
          automatic_release_tag: ${{ github.event.inputs.appVersion }}
          prerelease: false
          files: UEAssetToolkitGeneratorv${{ github.event.inputs.appVersion }}.zip
